// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnyq5QAsq3G2q0Tq5TK2nzua_TA0teLXo',
    appId: '1:709653324333:web:1029bfe9866a88d37b0ea4',
    messagingSenderId: '709653324333',
    projectId: 'todo-3320f',
    authDomain: 'todo-3320f.firebaseapp.com',
    storageBucket: 'todo-3320f.appspot.com',
    measurementId: 'G-TLFSSYN5HZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATgO-DiRDe_R0Wa6hxSPUXFfHT61fg7jU',
    appId: '1:709653324333:android:1ada6f3b52d793707b0ea4',
    messagingSenderId: '709653324333',
    projectId: 'todo-3320f',
    storageBucket: 'todo-3320f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5P5jv1Az103E6HIAWf_Skl6wiK02bvMU',
    appId: '1:709653324333:ios:2edcbee2865ed4ec7b0ea4',
    messagingSenderId: '709653324333',
    projectId: 'todo-3320f',
    storageBucket: 'todo-3320f.appspot.com',
    iosClientId:
        '709653324333-o50q2vsdl4vfq444el1jeueb4g19jr43.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5P5jv1Az103E6HIAWf_Skl6wiK02bvMU',
    appId: '1:709653324333:ios:2edcbee2865ed4ec7b0ea4',
    messagingSenderId: '709653324333',
    projectId: 'todo-3320f',
    storageBucket: 'todo-3320f.appspot.com',
    iosClientId:
        '709653324333-o50q2vsdl4vfq444el1jeueb4g19jr43.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );
}
